[Forms]
FormNames=MainForm@LeftDockPanel;MainForm@LeftDockPanel_PopupPanel;frmDockCodeExplorer;frmCodeInspector;frmDockFileBrowser;frmDockProjects;frmDockFTP_1;frmDockTemplates;frmDockCodeSnippets;TJvDockTabHostForm_frmDockCodeExplorer_frmCodeInspector_02009B60;MainForm@RightDockPanel;MainForm@RightDockPanel_PopupPanel;MainForm@TopDockPanel;MainForm@TopDockPanel_PopupPanel;MainForm@BottomDockPanel;MainForm@BottomDockPanel_PopupPanel;MainForm;frmSynWebSyntaxCheck;frmXdebugBreakpoints;frmXdebugContextVariables;frmXdebugEvaluate;frmXdebugEventLog;frmXdebugCallStack;frmXdebugWatches;frmDockDB;frmDockFTP;frmDockTodo;frmDockBug;frmDockDebugPHP;frmDockDebugPHPdoc;frmDockHelp;frmDockProjectOverview;frmDockFileSnapShots;frmDockInlineTodo;frmDockInlineBug;frmSearchResults;frmXdebugBreakpointsBase;frmXdebugContextVariablesBase;frmXdebugEvaluateBase;frmXdebugEventLogBase;frmXdebugCallStackBase;frmXdebugWatchesBase;frmProjectTodoBug;frmDockCodeLibraries;frmDockDatabaseConnections;frmDockDB_1;frmDockTodo_1;frmDockBug_1;frmDockDebugPHP_1;frmDockDebugPHPdoc_1;frmDockDebugTidy;frmDockHelp_1;frmDockProjectOverview_1;frmDockFileSnapShots_1;frmDockInlineTodo_1;frmDockInlineBug_1;

[Forms\MainForm@LeftDockPanel]
ParentName=MainForm
DockLeft=2
DockTop=111
DockRight=2
DockBottom=705
LastDockSiteName=
UnDockHeight=602
DockFormStyle=3
CanDocked=FALSE
EachOtherDocked=FALSE
LeftDocked=FALSE
TopDocked=FALSE
RightDock