処理,textarea,item_name,全半
処理,textarea,catch_copy,全半
置換,textarea,catch_copy,"\s\w{1,}\d{1,}「=」"
置換,textarea,catch_copy,\s「=」
処理,textarea,mobile_catch_copy,全半
置換,textarea,mobile_catch_copy,"\s\w{1,}\d{1,}「=」"
置換,textarea,mobile_catch_copy,\s「=」
選択,select,delivery_set_id,_H_
選択,radio,tax_flag,1
選択,radio,postage_flag,0
入力,input,postage,_S_
選択,radio,daibiki_flag,0
選択,radio,noshi_flag,0
選択,radio,sell_flag,1
選択,radio,panf_flag,0
選択,radio,ask_flag,0
選択,radio,stock_notify_flag,0
選択,radio,units_type,1
選択,radio,nokori,0
選択,checkbox,restore_inventory_flag,none
選択,checkbox,backorder_flag,none
選択,select,normal_delvdate_id,2
選択,select,backorder_delvdate_id,3
処理,textarea,catalog_caption,全半
整形,textarea,catalog_caption,0
処理,textarea,mobile_caption,全半
処理,textarea,smart_caption,全半
置換,textarea,smart_caption,http.*?aa00[012].jpg「=」_link_0-2
置換,textarea,smart_caption,_imgURL_「=」_splink_0-19
整形,textarea,smart_caption,0
処理,textarea,display_caption,全半
置換,textarea,display_caption,http.*em.jpg「=」_iteminfo_
置換,textarea,display_caption,http.*jpg「=」_link_0-19
置換,textarea,display_caption,_iteminfo_「=」https://image.rakuten.co.jp/patri/cabinet/04810226/item.jpg
整形,textarea,display_caption,0
入力,input,image_url1,_link_0
入力,input,image_url2,_link_1
入力,input,image_url3,_link_2
入力,input,image_url4,_link_3
入力,input,image_url5,_link_4
�