/*
 AddEventToLabel-1.0.0.min.js
 Copyright (c) 2014 Rakuten.Inc
 Date : 2014/9/18 18:00:00
*/
function AddEventToLabel(labelDialog){this.labelDialog=labelDialog}
AddEventToLabel.prototype={addEvent:function(){$(document).on("click",".PostLabelCreate",this.displayMsgList());$(document).on("click",".GetMessageList",this.displayMsgList())},displayMsgList:function(){var self=this;return function(event){self.resetDialog();self.displayLoader();self.unbindEvents();self.preventMultiplex();var $Dialog=self.displayDialog();self.labelDialog.set$Dialog($Dialog);self.labelDialog.set$Label($(this));self.setLabelDatas();self.set$AdditionalLabel();self.checkLabel();self.bindEvents()}},
unbindEvents:function(){$(document).off("click",".PostLabelCreate");$(document).off("click",".GetMessageList")},bindEvents:function(){var self=this;var callback=function(){$(document).on("click",".PostLabelCreate",self.displayMsgList());$(document).on("click",".GetMessageList",self.displayMsgList())};setTimeout(callback,500)},displayDialog:function(){var $Dialog=this.labelDialog.get$Dialog();var setting=this.labelDialog.getSettings();return $Dialog.dialog(setting)},set$AdditionalLabel:function(){var $Label=
this.labelDialog.get$Label();var $AdditionalLabel=$Label.closest("span.AdditionalLabel");this.labelDialog.set$AdditionalLabel($AdditionalLabel)},checkLabel:function(){var labelClass=this.labelDialog.getLabelClass();if(labelClass.indexOf("PostLabelCreate")>0){var message="PostLabelCreate#post";this.labelDialog.broadcast(message)}else if(labelClass.indexOf("GetMessageList")>0){var message="GetMessageList#get";this.labelDialog.broadcast(message)}},preventMultiplex:function(){var labelXhr=this.labelDialog.getLabelXhr();
try{labelXhr.abort()}catch(e){}},setLabelDatas:function(){var $Label=this.labelDialog.get$Label();this.setLabelClass($Label);this.setOrderNumber($Label);this.setBindId($Label);this.setLabelType($Label)},setLabelClass:function($Label){var labelClass=$Label.attr("class");this.labelDialog.setLabelClass(labelClass)},setOrderNumber:function($Label){var orderNumber=$Label.data("orderNumber");this.labelDialog.setOrderNumber(orderNumber)},setBindId:function($Label){var bindId=$Label.data("bindId");this.labelDialog.setBindId(bindId)},
setLabelType:function($Label){var labelType=$Label.data("labelType");this.labelDialog.setLabelType(labelType)},setLabelPath:function($Label){var labelPath=$Label.data("labelPath");this.labelDialog.setLabelPath(labelPath)},resetDialog:function(){this.resetData();var $Dialog=this.labelDialog.get$Dialog();$Dialog.empty()},resetData:function(){this.labelDialog.clearMessageResponseModel();this.labelDialog.clearUnitErrors();this.labelDialog.clearItemNames()},displayLoader:function(){var $Dialog=this.labelDialog.get$Dialog();
var $Loader=this.labelDialog.get$Loader();$Dialog.append($Loader)}};
