/*
 DisplayLabel-1.0.0.min.js
 Copyright (c) 2014 Rakuten.Inc
 Date : 2014/9/18 18:00:00
*/
function DisplayLabel(stickLabel){this.stickLabel=stickLabel}
DisplayLabel.prototype={display:function(){this.set$AdditionalLabels();var $AdditionalLabels=this.stickLabel.get$AdditionalLabels();if($AdditionalLabels.size()<=0)return;$.each($AdditionalLabels,this.stick())},set$AdditionalLabels:function(){var $AdditionalLabels=$("span.AdditionalLabel");this.stickLabel.set$AdditionalLabels($AdditionalLabels)},stick:function(){var self=this,datas=this.stickLabel.getDatas();return function(key,value){var $AdditionalLabel=$(this);self.stickLabel.set$AdditionalLabel($AdditionalLabel);
$AdditionalLabel.children("span.AdditionalLabelChild").remove();var orderNumber=$AdditionalLabel.children("span.LabelOrderNumber").text();var data=datas.results[orderNumber];self.stickLabel.setData(data);$.each(data,self.create())}},create:function(){var self=this;return function(index,value){self.stickLabel.setLabelIndex(index);var $AdditionalLabel=self.stickLabel.get$AdditionalLabel();var attributes={};attributes["class"]="AdditionalLabelChild";attributes.style="cursor: pointer";var $AdditionalLabelChild=
$("<span/>",attributes);self.stickLabel.set$AdditionalLabelChild($AdditionalLabelChild);self.mapData();self.makeMedicineLabel();self.appendImg();$AdditionalLabel.append($AdditionalLabelChild)}},mapData:function(){var $AdditionalLabelChild=this.stickLabel.get$AdditionalLabelChild();var data=this.stickLabel.getData();var index=this.stickLabel.getLabelIndex();var labelData={};labelData.orderNumber=data[index].orderNumber;labelData.bindId=data[index].bindId;labelData.labelType=data[index].labelType;labelData.labelPath=
data[index].labelPath;$AdditionalLabelChild.data(labelData)},makeMedicineLabel:function(){var message="MakeMedicineLabel#make";this.stickLabel.broadcast(message)},appendImg:function(){var $AdditionalLabelChild=this.stickLabel.get$AdditionalLabelChild();var labelPath=$AdditionalLabelChild.data("labelPath");if(labelPath==null)return;var url="https://image.rakuten.co.jp/com/img/rms/order-rb/label/";var attributes={};attributes.src=url+labelPath;attributes.alt=labelPath;attributes.title=this.getTitle();
var $img=$("<img>",attributes);$AdditionalLabelChild.append($img)},getTitle:function(){var $AdditionalLabelChild=this.stickLabel.get$AdditionalLabelChild();var labelType=$AdditionalLabelChild.data("labelType");var str="";if(this.isIconDrugTrue())str="¿·µ¬";if(labelType==0)str="¿·µ¬";if(labelType==1)str="ÊÖ¿®ÂÔ¤Á";if(labelType==2)str="Í×ÊÖ¿®";if(labelType==3)str="¾µÂúºÑ";return str},isIconDrugTrue:function(){var $AdditionalLabel=this.stickLabel.get$AdditionalLabel();if($AdditionalLabel.children("span.IconDrug").text()==
"true")return true;return false}};
