/*
 InitializeStickLabel-1.0.0.min.js
 Copyright (c) 2014 Rakuten.Inc
 Date : 2014/9/18 18:00:00
*/
function InitializeStickLabel(stickLabel){this.stickLabel=stickLabel}
InitializeStickLabel.prototype={initialize:function(){this.stickLabel.clearOrderNumbers();this.set$AdditionalLabels();this.makeOrderNumberList();if(this.isEmptyOrderNumbers()){this.displayLabel();return}this.getLabelList()},set$AdditionalLabels:function(){var $AdditionalLabels=$("span.AdditionalLabel");this.stickLabel.set$AdditionalLabels($AdditionalLabels)},makeOrderNumberList:function(){var $AdditionalLabels=this.stickLabel.get$AdditionalLabels();$.each($AdditionalLabels,this.checkLabel())},checkLabel:function(){var self=
this;return function(index,value){var $AdditionalLabel=$(this);self.stickLabel.set$AdditionalLabel($AdditionalLabel);var $AdditionalLabelChild=$AdditionalLabel.children("span.AdditionalLabelChild");self.stickLabel.set$AdditionalLabelChild($AdditionalLabelChild);if(self.hasLabel())return;self.setOrderNumbers()}},hasLabel:function(){var $AdditionalLabelChild=this.stickLabel.get$AdditionalLabelChild();if($AdditionalLabelChild.size()<=0)return false;return true},setOrderNumbers:function(){var $AdditionalLabel=
this.stickLabel.get$AdditionalLabel();var orderNumber=$AdditionalLabel.children("span.LabelOrderNumber").text();this.stickLabel.setOrderNumbers(orderNumber)},isEmptyOrderNumbers:function(){var orderNumbers=this.stickLabel.getOrderNumbers();if(orderNumbers.length<=0)return true;return false},displayLabel:function(){var message="DisplayLabel#display";this.stickLabel.broadcast(message)},getLabelList:function(){var message="GetLabelList#get";this.stickLabel.broadcast(message)},makeBalloon:function(){var $Balloon=
this.get$Balloon();var $Close=this.get$Close();var $Text=this.get$Text();$Balloon.append($Close);$Balloon.append($Text);$("div#detail").before($Balloon);this.stickLabel.set$Balloon($Balloon);this.addEventListeners();this.stickLabel.observable.next()},get$Balloon:function(){var $Balloon=$("<div/>");$Balloon.addClass("LabelBalloon");var css={};css.left="20px";$Balloon.css(css);return $Balloon},get$Close:function(){var $Close=$("<span/>");$Close.addClass("ui-icon");$Close.addClass("ui-icon-circle-close");
$Close.addClass("arrow_box-circle-close");return $Close},get$Text:function(){var $Text=$("<span/>");$Text.addClass("LabelErrTxt");var text="ラベル情報の取得に失敗しました。";$Text.text(text);return $Text},addEventListeners:function(){var $Balloon=this.stickLabel.get$Balloon();$Balloon.on("click","span.arrow_box-circle-close",this.close())},close:function(){var self=this;return function(){var $Balloon=self.stickLabel.get$Balloon();$Balloon.hide()}},initBefore:function(){this.makeBalloon()}};
