/*
 LabelDialog-1.0.0.min.js
 Copyright (c) 2014 Rakuten.Inc
 Date : 2014/9/18 18:00:00
*/
function LabelDialog(observable){observable.registerObserver(this);this.observable=observable;this.labelDialogController=new LabelDialogController(this);this.initializeLabelDialog=new InitializeLabelDialog(this);this.addEventToLabel=new AddEventToLabel(this);this.makeTemplates=new MakeTemplates(this);this.addEventToDialog=new AddEventToDialog(this);this.getMessageDetail=new GetMessageDetail(this);this.postMessageSend=new PostMessageSend(this);this.getMessageList=new GetMessageList(this);this.postLabelCreate=
new PostLabelCreate(this);this.displayErrDialog=new DisplayErrDialog(this)}
LabelDialog.prototype={$Dialog:{},msgData:{},labelClass:"",orderNumber:"",bindId:"",labelType:"",labelPath:"",$Label:{},$templates:{},$messageList:{},$messageDetail:{},$messageEdit:{},$messageErr:{},$currentPage:{},$returnPage:{},messageId:"",$MsgSubjec:{},$MsgBody:{},$AdditionalLabel:{},tmplOptions:{},labelXhr:{},$Loader:{},resultSending:{},update:function(message){this.labelDialogController.update(message)},broadcast:function(message){this.observable.broadcast(message)},getSettings:function(){return{modal:true,
closeText:"",closeOnEscape:true,resizable:false,show:{effect:"fade",duration:200},hide:{effect:"fade",duration:200},width:550,height:550,dialogClass:"quickViewDialog",position:{at:"top+450px"}}},getInitializeLabelDialog:function(){return this.initializeLabelDialog},getAddEventToLabel:function(){return this.addEventToLabel},getMakeTemplates:function(){return this.makeTemplates},getAddEventToDialog:function(){return this.addEventToDialog},getGetMessageDetail:function(){return this.getMessageDetail},
getPostMessageSend:function(){return this.postMessageSend},getGetMessageList:function(){return this.getMessageList},getPostLabelCreate:function(){return this.postLabelCreate},getDisplayErrDialog:function(){return this.displayErrDialog},get$Dialog:function(){return this.$Dialog},set$Dialog:function($Dialog){this.$Dialog=$Dialog},getMsgData:function(){return this.msgData},setMsgData:function(msgData){this.msgData=msgData},clearMessageResponseModel:function(){try{this.msgData.results.messageResponseModel=
[]}catch(e){}},clearUnitErrors:function(){try{this.msgData.unitErrors=[]}catch(e){}},clearItemNames:function(){try{this.msgData.itemNames=[]}catch(e){}},getLabelClass:function(){return this.labelClass},setLabelClass:function(labelClass){this.labelClass=labelClass},getOrderNumber:function(){return this.orderNumber},setOrderNumber:function(orderNumber){this.orderNumber=orderNumber},getBindId:function(){return this.bindId},setBindId:function(bindId){this.bindId=bindId},getLabelType:function(){return this.labelType},
setLabelType:function(labelType){this.labelType=labelType},getLabelPath:function(){return this.labelPath},setLabelPath:function(labelPath){this.labelPath=labelPath},get$Label:function(){return this.$Label},set$Label:function($Label){this.$Label=$Label},get$templates:function(){return this.$templates},set$templates:function($templates){this.$templates=$templates},get$messageList:function(){return this.$messageList},set$messageList:function($messageList){this.$messageList=$messageList},get$messageDetail:function(){return this.$messageDetail},
set$messageDetail:function($messageDetail){this.$messageDetail=$messageDetail},get$messageEdit:function(){return this.$messageEdit},set$messageEdit:function($messageEdit){this.$messageEdit=$messageEdit},get$messageErr:function(){return this.$messageErr},set$messageErr:function($messageErr){this.$messageErr=$messageErr},get$currentPage:function(){return this.$currentPage},set$currentPage:function($currentPage){this.$currentPage=$currentPage},get$returnPage:function(){return this.$returnPage},set$returnPage:function($returnPage){this.$returnPage=
$returnPage},getMessageId:function(){return this.messageId},setMessageId:function(messageId){this.messageId=messageId},get$MsgSubjec:function(){return this.$MsgSubjec},set$MsgSubjec:function($MsgSubjec){this.$MsgSubjec=$MsgSubjec},get$MsgBody:function(){return this.$MsgBody},set$MsgBody:function($MsgBody){this.$MsgBody=$MsgBody},get$AdditionalLabel:function(){return this.$AdditionalLabel},set$AdditionalLabel:function($AdditionalLabel){this.$AdditionalLabel=$AdditionalLabel},getTmplOptions:function(){return this.tmplOptions},
setTmplOptions:function(tmplOptions){this.tmplOptions=tmplOptions},getLabelXhr:function(){return this.labelXhr},setLabelXhr:function(labelXhr){this.labelXhr=labelXhr},get$Loader:function(){return this.$Loader},set$Loader:function($Loader){this.$Loader=$Loader},getResultSending:function(){return this.resultSending},setResultSending:function(resultSending){this.resultSending=resultSending}};
