/*
 PostMessageSend-1.0.0.min.js
 Copyright (c) 2014 Rakuten.Inc
 Date : 2014/9/18 18:00:00
*/
function PostMessageSend(labelDialog){this.labelDialog=labelDialog}
PostMessageSend.prototype={post:function(){$.ajax(this.getRequest()).done(this.displayMsgList()).fail(this.displaySysErrDialog())},sendMessage:function(){var self=this;return function(event){self.resetDialog();$(document).off("click",".sendMessage");var message="PostMessageSend#post";self.labelDialog.broadcast(message)}},resetDialog:function(){this.resetData();var $Dialog=this.labelDialog.get$Dialog();$Dialog.empty()},resetData:function(){this.labelDialog.clearMessageResponseModel();this.labelDialog.clearUnitErrors()},
getRequest:function(){var request={};request.url="https://order.rms.rakuten.co.jp/rms/mall/order/rb/vc";request.type="POST";request.dataType="json";request.traditional=true;request.data={"__event":"MessageSend","bindId":this.labelDialog.getBindId(),"speaker":0,"subject":this.labelDialog.get$MsgSubjec().val(),"body":this.labelDialog.get$MsgBody().val(),"orderNumber":this.labelDialog.getOrderNumber()};return request},displayMsgList:function(){var self=this;return function(data,status,xhr){self.emptyDialog();
if(data.resultCode=="E16-001"){self.labelDialog.setResultSending(data);self.processSucc();return}if(data.resultCode!="N00-000"){self.processFail(data);return}self.processSucc()}},processSucc:function(){this.updateLabel();var message="GetMessageList#get";this.labelDialog.broadcast(message)},processFail:function(data){this.setErrMsgData(data);this.set$messageEdit();this.printMessageEdit()},setErrMsgData:function(data){var nowMsgData=this.labelDialog.getMsgData();var errMsg={};errMsg.msg=data.msg;errMsg.resultCode=
data.resultCode;errMsg.unitErrors=data.unitErrors;var msgData=$.extend(true,{},nowMsgData,errMsg);this.labelDialog.setMsgData(msgData)},set$messageEdit:function(){var $messageEdit={};var data=this.labelDialog.getMsgData();var tmplOptions=this.labelDialog.getTmplOptions();try{$messageEdit=$.tmpl("messageEdit",data,tmplOptions)}catch(e){}this.labelDialog.set$messageEdit($messageEdit)},printMessageEdit:function(){var $messageEdit=this.labelDialog.get$messageEdit();this.printPage($messageEdit)},printPage:function($page){var $Dialog=
this.labelDialog.get$Dialog();$Dialog.append($page)},emptyDialog:function(){var $Dialog=this.labelDialog.get$Dialog();$Dialog.empty()},updateLabel:function(){var $AdditionalLabel=this.labelDialog.get$AdditionalLabel();var $AdditionalLabelChild=$AdditionalLabel.children("span.AdditionalLabelChild");$AdditionalLabelChild.remove();this.stickLabel()},stickLabel:function(){var message="InitializeStickLabel#initialize";this.labelDialog.broadcast(message)},displayErrDialog:function(){var message="DisplayErrDialog#display";
this.labelDialog.broadcast(message)},displaySysErrDialog:function(){var self=this;return function(xhr,status,error){var message="DisplayErrDialog#dispSysErr";self.labelDialog.broadcast(message)}}};
