/*
 AddEventToDialog-1.0.0.min.js
 Copyright (c) 2014 Rakuten.Inc
 Date : 2014/9/18 18:00:00
*/
function AddEventToDialog(labelDialog){this.labelDialog=labelDialog}
AddEventToDialog.prototype={add:function(){$(document).on("click",".messageList",this.displayMsgList());$(document).on("click",".messageDetail",this.displayMsgDetail());$(document).on("click",".messageEdit",this.displayMsgEdit());$(document).on("click",".messageReply",this.displayMsgReply());$(document).on("click",".sendMessage",this.sendMessage())},displayMsgList:function(){var self=this;return function(event){self.emptyDialog();self.displayLoader();self.resetData();var message="GetMessageList#get";
self.labelDialog.broadcast(message)}},displayMsgDetail:function(){var self=this;return function(event){self.emptyDialog();self.displayLoader();var messageId=$(this).children("span.messageId").text();self.labelDialog.setMessageId(messageId);var message="GetMessageDetail#get";self.labelDialog.broadcast(message)}},displayMsgEdit:function(){var self=this;return function(event){self.emptyDialog();self.setContents();self.resetData();self.clearText();var $messageEdit=self.labelDialog.get$messageEdit();self.printPage($messageEdit)}},
displayMsgReply:function(){var self=this;return function(event){self.emptyDialog();self.setContents();self.resetData();var $messageEdit=self.labelDialog.get$messageEdit();self.printPage($messageEdit)}},sendMessage:function(){var self=this;return function(event){self.emptyDialog();self.displayLoader();self.setContents();self.setNowPage();self.resetData();var message="PostMessageSend#post";self.labelDialog.broadcast(message)}},setNowPage:function(){var contents=this.getContents();this.setNowMsgData(contents);
this.set$messageEdit()},getContents:function(){var object={};object.results={};var $MsgSubjec=this.labelDialog.get$MsgSubjec();object.results.subject=$MsgSubjec.val();var $MsgBody=this.labelDialog.get$MsgBody();object.results.body=$MsgBody.val();return object},setNowMsgData:function(data){var nowMsgData=this.labelDialog.getMsgData();var object={};object.results=data.results;var msgData=$.extend(true,{},nowMsgData,object);this.labelDialog.setMsgData(msgData)},set$messageEdit:function(){var $messageEdit=
{};var data=this.labelDialog.getMsgData();var tmplOptions=this.labelDialog.getTmplOptions();try{$messageEdit=$.tmpl("messageEdit",data,tmplOptions)}catch(e){}this.labelDialog.set$messageEdit($messageEdit)},setContents:function(){var $messageEdit=this.labelDialog.get$messageEdit();this.set$MsgSubjec($messageEdit);this.set$MsgBody($messageEdit)},set$MsgSubjec:function($messageEdit){var $MsgSubjec=$messageEdit.find(".subjectText");this.labelDialog.set$MsgSubjec($MsgSubjec)},set$MsgBody:function($messageEdit){var $MsgBody=
$messageEdit.find(".body");this.labelDialog.set$MsgBody($MsgBody)},printPage:function($page){var $Dialog=this.labelDialog.get$Dialog();$Dialog.append($page)},registerPage:function($currentPage){this.set$returnPage();this.set$currentPage($currentPage)},set$returnPage:function(){var $currentPage=this.labelDialog.get$currentPage();this.labelDialog.set$returnPage($currentPage)},set$currentPage:function($currentPage){this.labelDialog.set$currentPage($currentPage)},emptyDialog:function(){var $Dialog=this.labelDialog.get$Dialog();
$Dialog.empty()},displayLoader:function(){var $Dialog=this.labelDialog.get$Dialog();var $Loader=this.labelDialog.get$Loader();$Dialog.append($Loader)},resetData:function(){this.labelDialog.clearMessageResponseModel();this.labelDialog.clearUnitErrors()},clearText:function(){try{var $MsgSubjec=this.labelDialog.get$MsgSubjec();$MsgSubjec.val("");var $MsgBody=this.labelDialog.get$MsgBody();$MsgBody.val("")}catch(e){}}};
