/*
 DatePicker.min.js 1.0.0
 Copyright (c) 2013 Rakuten.Inc
 Date : 2015/2/18 12:17:22
*/
function DatePicker(){}
DatePicker.prototype={datepicker:DatePicker.prototype,initDatepicker:function(datepickerId){$("#"+datepickerId).datepicker(datepicker.getDefaultSettings())},getDefaultSettings:function(){return{dateFormat:"yy-mm-dd",changeYear:true,changeMonth:true,showOn:"button",buttonText:"",buttonImage:"https://image.rakuten.co.jp/com/img/rms/icon/icon_calendar.gif",buttonImageOnly:true,minDate:new Date(1900,1-1,1),maxDate:new Date((new Date).getFullYear()+1,12-1,31),beforeShow:function(input,inst){inst.settings.dateFormat=
datepicker.getDateFormat(input)},beforeShowDay:function(day){return datepicker.getMethodOfDisplay(day)},onClose:function(dateText,inst){inst.settings.dateFormat="yy-mm-dd"}}},getMethodOfDisplay:function(day){try{var result;switch(day.getDay()){case 0:result=[true,"day-holiday"];break;case 6:result=[true,"day-6"];break;default:result=[true,""];break}return result}catch(e){return}},getDateFormat:function(element){try{var str=$(element).val();var year=str.substring(0,4);var month=str.substring(4,6);
var day=str.substring(6,8);if(datepicker.isDateFormat(year,month,day))return"yymmdd";else return"yy-mm-dd"}catch(e){return"yy-mm-dd"}},isDateFormat:function(year,month,day){try{var y=String(year);if(y.length!=4)return false;if(y.match(/^[^0-9]+$/))return false;y=Number(y);if(y<1900)return false;if(y>(new Date).getFullYear()+1)return false;var m=String(month);if(m.length!=2)return false;if(m.match(/^[^0-9]+$/))return false;m=Number(m);if(m<1)return false;if(m>12)return false;var d=String(day);if(d.length!=
2)return false;if(d.match(/^[^0-9]+$/))return false;d=Number(d);if(d<1)return false;if(d>31)return false;return true}catch(e){return false}},getToday:function(id){try{var date=new Date;var text=$.format.date(date,"yyyy-MM-dd");$("#"+id).val(text);return false}catch(e){return false}},getNextDay:function(id){try{var date=new Date;date.setTime(date.getTime()+60*60*24*1E3);var text=$.format.date(date,"yyyy-MM-dd");$("#"+id).val(text);return false}catch(e){return false}},getDayAfterNext:function(id){try{var date=
new Date;date.setTime(date.getTime()+60*60*24*1E3*2);var text=$.format.date(date,"yyyy-MM-dd");$("#"+id).val(text);return false}catch(e){return false}}};var datepicker=new DatePicker;function getToday(id){datepicker.getToday(id)}function getNextDay(id){datepicker.getNextDay(id)}function getDayAfterNext(id){datepicker.getDayAfterNext(id)}$(function(){$(".datepicker").each(function(){datepicker.initDatepicker(this.id)})});
