/*
 GetMessageDetail-1.0.0.min.js
 Copyright (c) 2014 Rakuten.Inc
 Date : 2014/9/18 18:00:00
*/
function GetMessageDetail(labelDialog){this.labelDialog=labelDialog}
GetMessageDetail.prototype={get:function(){$.ajax(this.getRequest()).done(this.displayMsgDetail()).fail(this.displaySysErrDialog())},getRequest:function(){var request={};request.url="https://order.rms.rakuten.co.jp/rms/mall/order/rb/vc";request.type="GET";request.dataType="json";request.traditional=true;request.data={"__event":"MessageDetail","orderNumber":this.labelDialog.getOrderNumber(),"messageId":this.labelDialog.getMessageId(),"bindId":this.labelDialog.getBindId()};return request},displayMsgDetail:function(){var self=
this;return function(data,status,xhr){self.emptyDialog();if(data.resultCode!="N00-000"){self.processFail(data);return}self.processSucc(data)}},processSucc:function(data){this.setMsgData(data);this.set$messages();this.printMessageDetail()},processFail:function(data){this.setErrMsgData(data);this.set$messageList();this.printMessageList()},setErrMsgData:function(data){var nowMsgData=this.labelDialog.getMsgData();var errMsg={};errMsg.msg=data.msg;errMsg.resultCode=data.resultCode;errMsg.unitErrors=data.unitErrors;
var msgData=$.extend(true,{},nowMsgData,errMsg);this.labelDialog.setMsgData(msgData)},set$messageList:function(){var $messageList={};var data=this.labelDialog.getMsgData();var tmplOptions=this.labelDialog.getTmplOptions();try{$messageList=$.tmpl("messageList",data,tmplOptions)}catch(e){}this.labelDialog.set$messageList($messageList)},printMessageList:function(){var $messageList=this.labelDialog.get$messageList();this.printPage($messageList)},printPage:function($page){var $Dialog=this.labelDialog.get$Dialog();
$Dialog.append($page)},emptyDialog:function(){var $Dialog=this.labelDialog.get$Dialog();$Dialog.empty()},setMsgData:function(data){var nowMsgData=this.labelDialog.getMsgData();var msgData=$.extend(true,{},nowMsgData,data);this.labelDialog.setMsgData(msgData)},set$messages:function(){var $messageDetail={};var $messageEdit={};var data=this.labelDialog.getMsgData();var tmplOptions=this.labelDialog.getTmplOptions();try{$messageDetail=$.tmpl("messageDetail",data,tmplOptions);$messageEdit=$.tmpl("messageEdit",
data,tmplOptions)}catch(e){}this.labelDialog.set$messageDetail($messageDetail);this.labelDialog.set$messageEdit($messageEdit)},printMessageDetail:function(){var $messageDetail=this.labelDialog.get$messageDetail();this.printPage($messageDetail)},registerPage:function($currentPage){this.set$returnPage();this.set$currentPage($currentPage)},set$returnPage:function(){var $currentPage=this.labelDialog.get$currentPage();this.labelDialog.set$returnPage($currentPage)},set$currentPage:function($currentPage){this.labelDialog.set$currentPage($currentPage)},
displaySysErrDialog:function(){var self=this;return function(xhr,status,error){var message="DisplayErrDialog#dispSysErr";self.labelDialog.broadcast(message)}}};
