/*
 InitializeLabelDialog-1.0.0.min.js
 Copyright (c) 2014 Rakuten.Inc
 Date : 2014/9/18 18:00:00
*/
function InitializeLabelDialog(labelDialog){this.labelDialog=labelDialog}
InitializeLabelDialog.prototype={initialize:function(){this.create();this.addEventToLabel();this.addEventToDialog();this.makeTemplates();this.makeLoader();this.setTmplOptions();this.labelDialog.observable.next()},create:function(){var $Dialog=$("<div/>",this.getAttributes());this.labelDialog.set$Dialog($Dialog);$("body").append($Dialog)},getAttributes:function(){return{"class":"LabelDialog","title":"メッセージ管理"}},addEventToLabel:function(){var message="AddEventToLabel#addEvent";this.labelDialog.broadcast(message)},
addEventToDialog:function(){var message="AddEventToDialog#add";this.labelDialog.broadcast(message)},makeTemplates:function(){var message="MakeTemplates#make";this.labelDialog.broadcast(message)},makeLoader:function(){var $Loader=$("<div/>");var prop={};prop.width="80px";prop.height="80px";prop.position="absolute";prop.top="0";prop.bottom="0";prop.left="0";prop.right="0";prop.margin="auto";$Loader.css(prop);$Loader.addClass("LabelLoader");var url="https://image.rakuten.co.jp/com/img/rms/backoffice/msg/loader.gif";
var attributes={};attributes.src=url;attributes.width="80px";attributes.height="80px";var $img=$("<img>",attributes);$Loader.append($img);this.labelDialog.set$Loader($Loader)},setTmplOptions:function(){var obj={},self=this;obj.log=function(value){console.log(value);return""};obj.decodeURIComponent=function(uriComponent){var urlStr="";try{urlStr=uriComponent.replace(/\+/g,"%20");urlStr=decodeURIComponent(urlStr);urlStr=urlStr.replace(/&/g,"&amp;")}catch(e){}return urlStr};obj.fmtReply=function(uriComponent){var urlStr=
"",str="";try{urlStr=uriComponent.replace(/\+/g,"%20");urlStr=decodeURIComponent(urlStr);urlStr=urlStr.replace(/&/g,"&amp;");var resultCode=self.labelDialog.getMsgData().resultCode;if(resultCode!="N00-000")str=urlStr;else{var array=urlStr.split(/\r\n|\r|\n/);$.each(array,function(){str+=">"+this+"\n"})}}catch(e){}return str};obj.readValueOf=function(speaker,messageStatus){if(speaker==1&&messageStatus==0)return"unread";if(speaker==1&&messageStatus!=0)return"read";return""};obj.readImgValueOf=function(speaker,
messageStatus){if(speaker==1&&messageStatus==0)return'<img src="https://image.rakuten.co.jp/com/img/rms/order-rb/msg/icon_unread.gif">';if(speaker==1&&messageStatus!=0)return'<img src="https://image.rakuten.co.jp/com/img/rms/order-rb/msg/icon_read.gif">';return""};obj.size=function(value){try{if(typeof value==="undefined")return[];if(value==null)return[]}catch(e){return[]}return value};obj.empty=function(value){try{if(typeof value==="undefined")return true;if(value==null)return true}catch(e){return true}return false};
obj.exists=function(value){try{if(typeof value==="undefined")return false;if(value==null)return false}catch(e){return false}return true};obj.convertEmp=function(value){try{if(typeof value==="undefined")return"";if(value==null)return""}catch(e){return""}return value};obj.isDisplaySubmit=function(statusId){if(statusId==5)return false;if(statusId==-1)return false;if(statusId==-2)return false;if(self.labelDialog.getLabelType()==3)return false;return true};this.labelDialog.setTmplOptions(obj)}};
