/*
 StickLabel-1.0.0.min.js
 Copyright (c) 2014 Rakuten.Inc
 Date : 2014/9/18 18:00:00
*/
function StickLabel(observable){observable.registerObserver(this);this.observable=observable;this.stickLabelController=new StickLabelController(this);this.initializeStickLabel=new InitializeStickLabel(this);this.getLabelList=new GetLabelList(this);this.makeMedicineLabel=new MakeMedicineLabel(this);this.displayLabel=new DisplayLabel(this)}
StickLabel.prototype={orderNumbers:[],data:{},datas:{},$AdditionalLabel:{},$AdditionalLabels:{},$AdditionalLabelChild:{},labelIndex:0,$Balloon:{},limited:"",update:function(message){var stickLabelController=this.getStickLabelController();stickLabelController.update(message)},broadcast:function(message){this.observable.broadcast(message)},getStickLabelController:function(){return this.stickLabelController},getInitializeStickLabel:function(){return this.initializeStickLabel},getGetLabelList:function(){return this.getLabelList},
getMakeMedicineLabel:function(){return this.makeMedicineLabel},getDisplayLabel:function(){return this.displayLabel},getOrderNumbers:function(){return this.orderNumbers},setOrderNumbers:function(orderNumber){this.orderNumbers.push(orderNumber)},clearOrderNumbers:function(){this.orderNumbers=[]},getData:function(){return this.data},setData:function(data){this.data=data},getDatas:function(){return this.datas},setDatas:function(datas){this.datas=datas},get$AdditionalLabel:function(){return this.$AdditionalLabel},
set$AdditionalLabel:function($AdditionalLabel){this.$AdditionalLabel=$AdditionalLabel},get$AdditionalLabelChild:function(){return this.$AdditionalLabelChild},set$AdditionalLabelChild:function($AdditionalLabelChild){this.$AdditionalLabelChild=$AdditionalLabelChild},get$AdditionalLabels:function(){return this.$AdditionalLabels},set$AdditionalLabels:function($AdditionalLabels){this.$AdditionalLabels=$AdditionalLabels},getLabelIndex:function(){return this.labelIndex},setLabelIndex:function(labelIndex){this.labelIndex=
labelIndex},get$Balloon:function(){return this.$Balloon},set$Balloon:function($Balloon){this.$Balloon=$Balloon},getLimited:function(){return this.limited},setLimited:function(limited){this.limited=limited}};
